name: work-1 //이름
on:
  push:
    branches:
      - main //메인에 푸쉬
jobs: // 어떤시행을 시킬지
  hello1: // hello1이라는 잡
    runs-on: ubuntu-latest
    steps:
      - name: sayHi
        run: echo "Hi"
      - name: sayMyName
        run: echo "${{ github.actor }}"
